# Generated by Django 2.2.7 on 2019-12-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete')], max_length=100, null=True),
        ),
    ]
