# Generated by Django 2.2.7 on 2019-12-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20191208_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectedunit',
            options={'verbose_name': 'AffectedUnit', 'verbose_name_plural': 'AffectedUnits'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.AddField(
            model_name='comment',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_comment', to='incident.Incident', verbose_name='incident'),
        ),
        migrations.AlterField(
            model_name='affectedunit',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_user', to=settings.AUTH_USER_MODEL, verbose_name='assigned_user'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentcategory', to='incident.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentsector', to='incident.Sector', verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('pending', 'pending'), ('in_progress', 'in_progress'), ('closed', 'closed')], max_length=100, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='related_domain',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.Incident', verbose_name='incident'),
        ),
        migrations.AlterField(
            model_name='related_domain',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='related_ip',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.Incident', verbose_name='incident'),
        ),
        migrations.AlterField(
            model_name='related_ip',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL, verbose_name='assigned_user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.Incident', verbose_name='incident'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('in_progress', 'in_progress'), ('complete', 'complete')], max_length=100, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_subject',
            field=models.CharField(max_length=255, verbose_name='task_subject'),
        ),
    ]
