# Generated by Django 2.2.7 on 2019-12-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_auto_20191210_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='affectedunit',
        ),
        migrations.AddField(
            model_name='affectedunit',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitsector', to='incident.Sector', verbose_name='sector'),
        ),
        migrations.AddField(
            model_name='incident',
            name='affectedunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentunit', to='incident.AffectedUnit', verbose_name='affectedunit'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='timestamp'),
        ),
    ]
