# Generated by Django 2.2.7 on 2019-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': 'modified_on', 'ordering': ('-modified_on', '-created_on')},
        ),
        migrations.AddField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
